FROM node:lts-alpine

WORKDIR /app

#Copies all files from nasaproject into app
COPY package*.json ./

COPY client/package*.json client/
RUN npm run install-client --omit=dev

COPY server/package*.json server/
RUN npm run install-server --omit=dev

COPY client/ client/
RUN npm run build --prefix client

COPY server/ server/

#Setting user to node reduces what user can do compared to root user
USER node

#Only need to start server since build files go into server
CMD [ "npm", "start", "--prefix", "server"]

EXPOSE 8000